name: moxxmpp
description: A pure-Dart XMPP library
version: 0.4.0
homepage: https://codeberg.org/moxxy/moxxmpp
publish_to: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  collection: ^1.16.0
  cryptography: ^2.0.5
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  hex: ^0.2.0
  json_serializable: ^6.3.1
  logging: ^1.0.2
  meta: ^1.7.0
  moxlib:
   hosted: https://git.polynom.me/api/packages/Moxxy/pub
   version: ^0.1.5
  omemo_dart:
    hosted: https://git.polynom.me/api/packages/PapaTutuWawa/pub
    version: ^0.4.3
  random_string: ^2.3.1
  saslprep: ^1.0.2
  synchronized: ^3.0.0+2
  uuid: ^3.0.5
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.11
  test: ^1.16.0
  very_good_analysis: ^3.0.1
